# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainGUI_CounterLogger.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QGroupBox, QHeaderView,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 660)
        font = QFont()
        font.setFamilies([u"Arial"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(15, 270, 356, 186))
        self.lbl_counter = QLabel(self.groupBox)
        self.lbl_counter.setObjectName(u"lbl_counter")
        self.lbl_counter.setGeometry(QRect(15, 40, 321, 136))
        font1 = QFont()
        font1.setFamilies([u"DB Adman X"])
        font1.setPointSize(150)
        font1.setBold(True)
        self.lbl_counter.setFont(font1)
        self.lbl_counter.setStyleSheet(u"color: rgb(16, 128, 64);")
        self.lbl_counter.setScaledContents(True)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 10, 126, 31))
        font2 = QFont()
        font2.setFamilies([u"DB Adman X"])
        font2.setPointSize(20)
        font2.setBold(True)
        self.label_5.setFont(font2)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 10, 51, 31))
        self.label_7.setFont(font2)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(15, 465, 356, 166))
        self.lbl_capacity = QLabel(self.groupBox_2)
        self.lbl_capacity.setObjectName(u"lbl_capacity")
        self.lbl_capacity.setGeometry(QRect(15, 50, 326, 106))
        font3 = QFont()
        font3.setFamilies([u"DB Adman X"])
        font3.setPointSize(100)
        font3.setBold(True)
        self.lbl_capacity.setFont(font3)
        self.lbl_capacity.setStyleSheet(u"color: rgb(252, 1, 7);")
        self.lbl_capacity.setScaledContents(True)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 151, 31))
        self.label_8.setFont(font2)
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(165, 10, 141, 31))
        self.label_10.setFont(font2)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(15, 10, 356, 191))
        self.lbl_date = QLabel(self.groupBox_3)
        self.lbl_date.setObjectName(u"lbl_date")
        self.lbl_date.setGeometry(QRect(30, 135, 266, 51))
        font4 = QFont()
        font4.setFamilies([u"DB Adman X"])
        font4.setPointSize(50)
        font4.setBold(True)
        self.lbl_date.setFont(font4)
        self.lbl_time = QLabel(self.groupBox_3)
        self.lbl_time.setObjectName(u"lbl_time")
        self.lbl_time.setGeometry(QRect(10, 15, 331, 121))
        font5 = QFont()
        font5.setFamilies([u"DB Adman X"])
        font5.setPointSize(140)
        font5.setBold(True)
        self.lbl_time.setFont(font5)
        self.lbl_time.setScaledContents(True)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(15, 210, 356, 51))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 111, 31))
        self.label_3.setFont(font2)
        self.lbl_StartTime = QLabel(self.groupBox_4)
        self.lbl_StartTime.setObjectName(u"lbl_StartTime")
        self.lbl_StartTime.setGeometry(QRect(130, 10, 216, 31))
        font6 = QFont()
        font6.setFamilies([u"DB Adman X"])
        font6.setPointSize(30)
        font6.setBold(True)
        self.lbl_StartTime.setFont(font6)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1085, 460, 181, 31))
        self.label_12.setFont(font2)
        self.gp_camera = QGraphicsView(self.centralwidget)
        self.gp_camera.setObjectName(u"gp_camera")
        self.gp_camera.setGeometry(QRect(380, 10, 891, 441))
        self.btn_save = QPushButton(self.centralwidget)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(1085, 495, 101, 41))
        font7 = QFont()
        font7.setFamilies([u"DB Adman X"])
        font7.setPointSize(18)
        font7.setBold(True)
        self.btn_save.setFont(font7)
        self.btn_delete = QPushButton(self.centralwidget)
        self.btn_delete.setObjectName(u"btn_delete")
        self.btn_delete.setGeometry(QRect(1085, 540, 101, 41))
        self.btn_delete.setFont(font7)
        self.tb_logger = QTableWidget(self.centralwidget)
        self.tb_logger.setObjectName(u"tb_logger")
        self.tb_logger.setGeometry(QRect(380, 460, 691, 191))
        self.btn_exit = QPushButton(self.centralwidget)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setGeometry(QRect(1085, 605, 126, 41))
        self.btn_exit.setFont(font7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle("")
        self.lbl_counter.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19\u0e17\u0e35\u0e48\u0e1c\u0e25\u0e34\u0e15\u0e44\u0e14\u0e49", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"(\u0e0a\u0e34\u0e49\u0e19)", None))
        self.groupBox_2.setTitle("")
        self.lbl_capacity.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0e04\u0e27\u0e32\u0e21\u0e40\u0e23\u0e47\u0e27\u0e01\u0e32\u0e23\u0e1c\u0e25\u0e34\u0e15", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"(\u0e0a\u0e34\u0e49\u0e19/\u0e19\u0e32\u0e17\u0e35)", None))
        self.groupBox_3.setTitle("")
        self.lbl_date.setText(QCoreApplication.translate("MainWindow", u"00-00-0000", None))
        self.lbl_time.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.groupBox_4.setTitle("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u0e40\u0e27\u0e25\u0e32\u0e40\u0e23\u0e34\u0e48\u0e21\u0e07\u0e32\u0e19 :", None))
        self.lbl_StartTime.setText(QCoreApplication.translate("MainWindow", u"HH:MM:SS", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e1c\u0e25\u0e34\u0e15", None))
        self.btn_save.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.btn_delete.setText(QCoreApplication.translate("MainWindow", u"\u0e25\u0e1a", None))
        self.btn_exit.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e1a\u0e01\u0e32\u0e23\u0e17\u0e33\u0e07\u0e32\u0e19", None))
    # retranslateUi

